function [Timestamp, SystempowergeneratedkW] = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  [TIMESTAMP, SYSTEMPOWERGENERATEDKW] = IMPORTFILE(FILE) reads data
%  from the first worksheet in the Microsoft Excel spreadsheet file
%  named FILE.  Returns the data as column vectors.
%
%  [TIMESTAMP, SYSTEMPOWERGENERATEDKW] = IMPORTFILE(FILE, SHEET) reads
%  from the specified worksheet.
%
%  [TIMESTAMP, SYSTEMPOWERGENERATEDKW] = IMPORTFILE(FILE, SHEET,
%  DATALINES) reads from the specified worksheet for the specified row
%  interval(s). Specify DATALINES as a positive scalar integer or a
%  N-by-2 array of positive scalar integers for dis-contiguous row
%  intervals.
%
%  Example:
%  [Timestamp, SystempowergeneratedkW] = importfile("C:\Users\jdv223\University of Kentucky\Dvorak Lab - Documents\Aquaculture\SAM Analysis\Jackson_3kW.xlsx", "Sheet1", [2, 192721]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jan-2021 10:01:12

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 192721];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Timestamp", "SystempowergeneratedkW"];
opts.VariableTypes = ["datetime", "double"];

% Specify variable properties
opts = setvaropts(opts, "Timestamp", "InputFormat", "");

% Import the data
tbl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
Timestamp = tbl.Timestamp;
SystempowergeneratedkW = tbl.SystempowergeneratedkW;
end